---
version: "2.1"
services:
  vault-server:
    image: vault
    container_name: vault-server
    ports:
      - 8200:8200
    volumes:
      - ./logs:/vault/logs
      - ./file:/vault/file
      - ./config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
    restart: always